### ISSUE TITLE
Macro expansion

### ISSUE THREAD

**Issue by eddelbuettel** [rdrr-io/rdrr-issues#1]
Thanks for running [rdrr.io](http://rdrr.io).

I somewhat recently learned about new macros in the Rd files; they are documented at the [end of section 2.13 of WRE](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#User_002ddefined-macros).  So I used them in a recent package -- which doesn't [render right at rdrr.io](https://rdrr.io/cran/anytime/man/anytime-package.html) -- see eg the page title of that link. 

Would be nice if you could look into that.  Thanks.

**Comment by ihowson** [comment]
Will do. Thanks!

**Comment by ihowson** [comment]
Should be fixed now (at least for anytime). Thanks for the report!

**Comment by eddelbuettel** [comment]
Nice, thank you. I also checked my other new package nanotime and it looks correct now too.

**Comment by rubak** [comment]
Sorry for commenting on a closed issue -- please let me know if you want me to open a new one.

I see the same issue for the `spatstat` package which uses local macro definitions in the directory [man/macros/](https://github.com/spatstat/spatstat/tree/master/man/macros) as documented the same place of WRE. It would be great if these definitions could be used to expand the macros on <https://rdrr.io>. Any `spatstat` help page (e.g. [affine](https://rdrr.io/cran/spatstat/man/affine.html)) can be used to see the missing macro expansion.

The same issue applies to `spatstat.utils` and `spatstat.data`.
