### ISSUE TITLE
Request to delete a repo

### ISSUE THREAD

**Issue by jprlink** [rdrr-io/rdrr-issues#100]
Hello, 

I am working for the organization Impact Initiatives that published the package found on https://rdrr.io/github/WASH-Severity-Classification/WSC_processing/#vignettes.

I changed the repository to private status half a year ago, but it is still fully visible on rdrr.io. Can you please delete it from that page and make sure that it cannot be found in search results? It is very urgent.

Many thanks in advance,

Jasper Linke

**Comment by ihowson** [comment]
I've removed it. Thanks for getting in touch!

**Comment by jprlink** [comment]
Thank you!
