### ISSUE TITLE
shape based distance for multiple time series does not  work

### ISSUE THREAD

**Issue by yasamanrezvani** [rdrr-io/rdrr-issues#101]
I have a gene expression matrix and would like to calculate the distance between every pair of genes. I converted genes expression into a list of expression (consider it as multiple time series or 10 genes) and used the following command as suggested in the manual of dtwclustering:

proxy::dist(time_series[1:10],  time_series[1:10]), method = "SBD",  return.shifted = TRUE)

However, the values are exactly matching the basic dist() fuction in r with default method to be "euclidean". Seems the "SDB" method is not applied. 

Can you please help me with this as I need to use a s**hape base method** to calculate the similarity/distance between the genes. 

Thanks,

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
