### ISSUE TITLE
lavaanToGraph doesn't recognize parameters fixed to 0

### ISSUE THREAD

**Issue by mrhemtulla** [rdrr-io/rdrr-issues#102]
If a parameter is fixed to zero in lavaan by specifying the parameter and fixing it with 0*, lavaanToGraph seems to read that as though the parameter is estimated, and the independence is not coded. Reproducible example below: 

```
Sigma <- matrix(c(1, .5, .5, .5, 1, .5, .5, .5, 1), 3, 3)
colnames(Sigma) <- c("X", "M", "Y")
Model <- 'Y ~ M
          M ~ X
          X ~ 0*Y'

fitModel <- sem(model = Model, sample.cov = Sigma, sample.nobs = 100)
param <- parameterEstimates(fitModel)
dag <- lavaanToGraph(param)
plot(dag)
```

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
