### ISSUE TITLE
Request to delete a repo

### ISSUE THREAD

**Issue by andronikoss** [rdrr-io/rdrr-issues#104]
Hello,

colleagues of mine work on a new version of the package "desk" (didactic econometrics starter kit). An early version can still be found here:
[https://rdrr.io/github/andronikoss/desk/](https://rdrr.io/github/andronikoss/desk/?fbclid=IwAR0v7Q7RSaC_43qZT8Wscp64hHvYxlomcZUjUCeQ3EBXhp_34d6GKHO_oQY)

I changed the repository to private status, but it is still fully visible on rdrr.io. Can you please delete it from that page and make sure that it cannot be found in search results?

Many thanks in advance,

Andronikoss

**Comment by ihowson** [comment]
I've removed it. Thanks for getting in touch!
