### ISSUE TITLE
Request to delete a repo from the website

### ISSUE THREAD

**Issue by ZheFrench** [rdrr-io/rdrr-issues#105]
Hi,

We  found our package BulksignalR (https://rdrr.io/github/ZheFrench/BulksignalR/) on your website .
This package was first public and then we moved to a private account.
Still, the first version remains on your website. 
Could you remove it from your index , please ?

Thanks

**Comment by ihowson** [comment]
I've removed it. Thanks for getting in touch!

**Comment by ZheFrench** [comment]
Hi,

We found our package BulksignalR ([rdrr.io/github/ZheFrench/BulksignalR](https://rdrr.io/github/ZheFrench/BulksignalR/)) on your website .
This package is in open access because it's in process of being pushed to bioconductor but not totally reviewed yet.
In the meantine, could you remove it from your index , please ?

Thanks

**Comment by ihowson** [comment]
Apologies for the delay. I've removed it. Thanks for getting in touch!
