### ISSUE TITLE
Error in the function EQUIVNONINF:sgnrk 

### ISSUE THREAD

**Issue by vargabalint92** [rdrr-io/rdrr-issues#106]
Line:

`crit <- sqrt(qchisq(0.05,1,(eps/sigmah)**2)) `

is wrong
alpha is hard coded.

[see here](https://rdrr.io/cran/EQUIVNONINF/src/R/sgnrk.R)

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
