### ISSUE TITLE
Categorical Feature Issue

### ISSUE THREAD

**Issue by thtarekce** [rdrr-io/rdrr-issues#108]
# Check if more categorical features were output over the feature space
if (max(private$categorical_feature) > length(private$colnames))

Here, length(private$colnames) should be length(colnames(private)), since colnames is a function in R not an attribute.
Hence, there is always showing an error: 
 "lgb.self.get.handle: supplied a too large value in categorical_feature: "

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
