### ISSUE TITLE
TPM 

### ISSUE THREAD

**Issue by laetitiacollet** [rdrr-io/rdrr-issues#109]
Hi, 

I try to use TPM fonction with 2 data : one data frame with gene in row and samples in column and another data with gene in row and gene lenghts in column
nrow raw count = nrow gene lenght and they are in the same ordre

However when I apply the function I have a message error saying the the data have not the same dimension

How I can fix it ? 

thanks for your reply !

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
