### ISSUE TITLE
Request to remove packages

### ISSUE THREAD

**Issue by kvten** [rdrr-io/rdrr-issues#113]
Request to remove these packages:

- https://rdrr.io/github/kenf1/RR-R/
- https://rdrr.io/github/kenf1/RR-R-Package/
- https://rdrr.io/github/kenf1/KF.QoL/

**Comment by ihowson** [comment]
I've removed them. Thanks for getting in touch!

**Comment by paulmeinz** [comment]
I would like to request that you remove this package from your page. 

https://rdrr.io/github/paulmeinz/hawkTrackHelp/

**Comment by ihowson** [comment]
@paulmeinz done!

**Comment by paulmeinz** [comment]
Thank you!
