### ISSUE TITLE
Request to remove packages 

### ISSUE THREAD

**Issue by gogo4reve** [rdrr-io/rdrr-issues#114]
Hello,

Request to remove these packages:

https://rdrr.io/github/seoxx217/Homework/
https://rdrr.io/github/seoxx217/Homework/src/TemplateforbuildingRpackage.R
https://rdrr.io/github/seoxx217/Homework/api/
https://rdrr.io/github/seoxx217/Homework/f/
https://rdrr.io/github/seoxx217/Homework/man/

Thank you.

**Comment by ihowson** [comment]
I've removed them. Thanks for getting in touch!
