### ISSUE TITLE
Error in abcd calibration code

### ISSUE THREAD

**Issue by chethanram7009** [rdrr-io/rdrr-issues#115]
op_cal=abcdCalibrate(0.8,150,0.5,0.8, Q.obs = Q.obs, metric = "KGE")
Error in abcd_qest(...) : could not find function "abcd_qest"

Can you please explain What's the mistake I'm doing?

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
