### ISSUE TITLE
Error with vectors and xml_nodeset objects, fetch_xg_data

### ISSUE THREAD

**Issue by dthorrington** [rdrr-io/rdrr-issues#118]
Hello,

[Chrisjb/fploptimiser: Fantasy Premier League Team Optimisation](https://rdrr.io/github/Chrisjb/fploptimiser/)

When running df_xp <- fetch_xg_data() at the very beginning, either with a defined year or without, I get an error about vectors where a xml_nodeset object is defined.

_Error in `stringr::str_subset()`:
! `string` must be a vector, not a <xml_nodeset> object._

I've checked what's going on in fetch_xg_data.R and it's in the definition of epl_teams_raw, but I'm none-the-wiser. What's my mistake, please?

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
