### ISSUE TITLE
adonis2 in version 2.6-8 giving the wrong results

### ISSUE THREAD

**Issue by greagroenewald** [rdrr-io/rdrr-issues#123]
`When Performing a PERMANOVA my previous vegan package (v2.6-6) gave the following output when I ran the code:
`
```
P.div <- adonis2(P.dist~Depth*Marina, data = G, method='bray')
P.div

```

> Terms added sequentially (first to last)
> 
>                       Df   SumsOf Sqs Mean Sqs     F.    Model  R2 Pr(>F)    
> Depth              1    0.3659         0.36590  1.4379 0.02541  0.176    
> Marina             1    2.5143         2.51432  9.8806 0.17463  0.001 ***
> Depth:Marina  1    0.3206         0.32062  1.2599 0.02227  0.258    
> Residuals       44   11.1967        0.25447              0.77768           
> Total               47   14.3976                                  1.00000           
> 
> But with the updated van 2.6-8 I'm getting the following result with the same code:
> Permutation test for adonis under reduced model
> Permutation: free
> Number of permutations: 999
> 
> adonis2(formula = P.dist ~ Depth * Marina, data = G, method = "bray")
>               Df SumOfSqs      R2      F Pr(>F)    
> Model     3   3.2008 0.22232 4.1928  0.001 ***
> Residual 44  11.1967 0.77768                  
> Total       47  14.3976 1.00000                  
> 
> Is there a different way to write the code with the update or is it a but in the code, because if I run the same code as:

```
P.div <- adonis(P.dist~Depth*Marina, data = G, method='bray')
P.div$aov.tab
```

> I get the error:
> Warning message:
> In adonis(P.dist ~ Depth * Marina, data = G, method = "bray") :
>   'adonis' is deprecated.
> Use 'adonis2' instead.
> See help("Deprecated") and help("vegan-deprecated").
> 
> but it gives me the right results.
> Is there any help you can give?

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
