### ISSUE TITLE
khb with weighted data

### ISSUE THREAD

**Issue by Baky-cisse** [rdrr-io/rdrr-issues#127]
Hello
I have weighted data and I'd like to compare my 2 regression models but I get an error message that I can't resolve:

`full <- svyglm(sportrec ~ age10 + difffinancrec, 
               family=quasibinomial(link="logit"), design=HLD_FRH)

red <- svyglm(sportrec ~ age10, 
              family=quasibinomial(link="logit"), design=HLD_FRH)`

 [>] Mediators: difffinancrec
Error in svyglm.survey.design(formula = sportrec ~ age10 + KHB__KHB__difffinancrecNo,  : 
  all variables must be in design= argument

Thanks to help me

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
