### ISSUE TITLE
Open rdrr.io from within R

### ISSUE THREAD

**Issue by meriops** [rdrr-io/rdrr-issues#21]
I may have missed it but it would be nice if one could open help pages on rdrr.io from within R with `?function_name`, similar to what is done in RDocumentation.

Also, when on the page for a given function, an extra "button" to actually see the code could be useful...

**Comment by ihowson** [comment]
There's no `?function_name` functionality yet, but it's a great idea!

For the latter, do you mean a button to go from a man page to function's source code? If so, it'll be ready soon!

**Comment by ihowson** [comment]
> Also, when on the page for a given function, an extra "button" to actually see the code could be useful...

This has been implemented. 

> would be nice if one could open help pages on rdrr.io from within R with ?function_name

I don't have a dedicated package, but the `websearchr` package might be of interest: https://rdrr.io/cran/websearchr/man/rdrr_io.html
