### ISSUE TITLE
Index does not handle renames

### ISSUE THREAD

**Issue by jimhester** [rdrr-io/rdrr-issues#22]
E.g. https://rdrr.io/github/jimhester/printr/ was renamed to lookup, but the index still uses the old package name.

**Comment by ihowson** [comment]
Hi Jim -- thanks for the report!

GitHub repos are pretty slow to update due to the volume of data involved -- I'm guessing around two weeks. I'll manually schedule an update for printr->lookup today.

**Comment by jimhester** [comment]
FWIW the rename happened in July https://github.com/jimhester/lookup/commit/db06f98ead8d1129440b289a6ad423c012225672, so there is more going on than just a stale index

**Comment by ihowson** [comment]
Ah, that's interesting! 

We've only been loading GitHub packages for a week now (literally have not finished the first pass of import yet) but we should have detected the rename/redirect of `printr` to `lookup` if it happened in July. I'll fix it up for future builds.

**Comment by ihowson** [comment]
`lookup` and `printr` have been re-processed. They might take half an hour to come through the CDN. Handling renames properly is on the development queue. Thanks again!
