### ISSUE TITLE
Installing scran on dev version of R 3.4.1

### ISSUE THREAD

**Issue by cguzzo** [rdrr-io/rdrr-issues#25]
Hi!

I'm trying to install scran on the dev 3.4.1 but get an error message and can't load the library. Is this an R issue or is there a fix? I would like to test mnnCorrect()

“installation of package ‘scran’ had non-zero exit status”

Thanks
Charlotte

**Comment by ihowson** [comment]
Hi Charlotte,

Unfortunately, we're not able to provide support for individual packages. You might get better results by contacting the package authors or asking your question on StackOverflow.

**Comment by cguzzo** [comment]
Hi @ihowson, Thanks for pointing me in the right direction, the problem was indeed independent from scran.
