### ISSUE TITLE
Function names sometimes have inital letters chopped off (especially if starts with an ``.``)

### ISSUE THREAD

**Issue by trevorld** [rdrr-io/rdrr-issues#29]
Example from one of my packages "optparse" is that the non-exported, non-documented, and not intended for public use function ``.is_long_flag``  is instead listed as ``s_long_flag`` i.e. the initial ``.i`` has been chopped off.  On the other hand ``.requires_argument`` is instead listed as ``requires_argument`` and only the initial ``.`` has been chopped off.

https://rdrr.io/github/trevorld/optparse/api/

**Comment by ihowson** [comment]
Should be fixed -- see bottom of https://rdrr.io/github/trevorld/optparse/src/R/optparse.R

Let me know if you see any more formatting issues.

Thanks for the report!
