### ISSUE TITLE
Trouble installing package from CRAN

### ISSUE THREAD

**Issue by jimstigler** [rdrr-io/rdrr-issues#31]
Hi, I'm trying to install the package "supernova" to run in your web interface. I searched on your site and quickly found the package. But I can't get it to install. Am I doing something wrong? Thanks.

**Comment by ihowson** [comment]
Hi Jim -- are you trying to install something into Snippets (https://rdrr.io/snippets)? It won't let you install new packages. If there's something missing, let me know and I can preinstall it.

**Comment by jimstigler** [comment]
Yes, I would appreciate it if you would install the package supernova,
available on CRAN. Thanks.

**Comment by ihowson** [comment]
Hi Jim,

It's installed now. Let me know if you have any issues.

**Comment by jimstigler** [comment]
Hi Ian, thanks. Is it possible to also update these packages from CRAN:

   - mosaic
   - mosaicData
   - mosaicCore
   - Matrix
   - ggformula
   - ggplot2
   - lattice
   - dplyr

Sorry, I know I'm asking a lot...
Jim

**Comment by ihowson** [comment]
I updated a bunch of stuff today when I added `supernova`. Current state is:

```
[1] mosaicCore_0.4.0  mosaic_1.1.0      Matrix_1.2-14     mosaicData_0.14.0
[5] ggformula_0.6     ggplot2_3.0.0     lattice_0.20-35   dplyr_0.7.6      
```

Are they suitable?

**Comment by jimstigler** [comment]
These are the ones that are still far behind and that I'd like to see updated:
mosaicCore_0.6.0  
mosaic_1.4.0 
mosaicData_0.17.0   
ggformula_0.9.0  
Thanks!

**Comment by ihowson** [comment]
OK, I've updated those. Now we're at:

```
[1] mosaicCore_0.6.0  mosaic_1.4.0      Matrix_1.2-14     mosaicData_0.17.0
[5] ggformula_0.9.0   ggstance_0.3.1    ggplot2_3.0.0     lattice_0.20-35  
[9] dplyr_0.7.6      
```

**Comment by jimstigler** [comment]
Thank you so much!
