### ISSUE TITLE
error install gmp from git repository

### ISSUE THREAD

**Issue by pgreisen** [rdrr-io/rdrr-issues#32]
Hi , 

I am trying to plot a PSSM using Logolas but I have had a couple of issues: Firstly, I get the following package error trying to install devtools - devtools::install_github('kkdey/Logolas') but get the following error:
Error in i.p(...): (converted from warning) installation of package ‘gmp’ had non-zero exit status
Traceback:

If I continue ignoring the error - I get the following new error

library(Logolas)
sequence <- c("CTATTGT", "CTCTTAT", "CTATTAA", "CTATTTA", "CTATTAT", "CTTGAAT",
              "CTTAGAT", "CTATTAA", "CTATTTA", "CTATTAT", "CTTTTAT", "CTATAGT",
              "CTATTTT", "CTTATAT", "CTATATT", "CTCATTT", "CTTATTT", "CAATAGT",
              "CATTTGA", "CTCTTAT", "CTATTAT", "CTTTTAT", "CTATAAT", "CTTAGGT",
              "CTATTGT", "CTCATGT", "CTATAGT", "CTCGTTA", "CTAGAAT", "CAATGGT")

logomaker(sequence, type = "Logo")

Error in logomaker(sequence, type = "Logo"): unused argument (type = "Logo")
Traceback:

I am running in jupyter notebook with the following settings:

R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: macOS  10.14

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Logolas_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17    digest_0.6.18   crayon_1.3.4    IRdisplay_0.4.4
 [5] grid_3.4.1      repr_0.15.0     jsonlite_1.5    magrittr_1.5   
 [9] evaluate_0.11   stringi_1.2.4   uuid_0.1-2      IRkernel_0.8.12
[13] tools_3.4.1     stringr_1.3.1   compiler_3.4.1  base64enc_0.1-3
[17] htmltools_0.3.6 pbdZMQ_0.3-2   

How to fix the problem - any hints or suggestions appreciated

**Comment by ihowson** [comment]
Thanks for getting in touch!

Unfortunately, I'm not the author of the packages on https://rdrr.io, and I'm not able to provide support for them. You should get in touch with the package authors listed on the package page.

Thanks,
Ian
