### ISSUE TITLE
Bad Description

### ISSUE THREAD

**Issue by Schmidtbit** [rdrr-io/rdrr-issues#33]
Hello, 

regarding: https://rdrr.io/github/robjhyndman/fpp/man/gasoline.html

The file gasoline.csv only has 745 rows. 

The descriptions says: "Weekly data beginning 2 February 1991, ending 20 January 2017. Units are "million barrels per day".

This description makes no sense because because weekly data taken from Feb 2, 1991 (which is a Saturday) up until Jan 20, 2017 (which is a Friday) results in 1356 weeks (or 26 years)

745 rows of weekly data would only give results up until May 7, 2005 (14 years)

Please clarify or provide a link to your source. 

Thank you,

**Comment by ihowson** [comment]
Hi Andrea,

This issue tracker is just the for rdrr.io website. Issues with individual packages should be sent to the directly to the package authors. Sorry!
