### ISSUE TITLE
MIME type

### ISSUE THREAD

**Issue by szepeviktor** [rdrr-io/rdrr-issues#35]
What could be the (non-)standard MIME type for ˙.properties` file?

e.g. https://my.sendinblue.com/public/language2/lang_en.properties

**Comment by ihowson** [comment]
Is this an issue relevant to rdrr.io?

**Comment by szepeviktor** [comment]
Maybe not :)

Googling for the first line of the above file reveals https://rdrr.io/bioc/RnBeads/man/rnb.build.index.html
