### ISSUE TITLE
LEfSe on changes

### ISSUE THREAD

**Issue by aneviere** [rdrr-io/rdrr-issues#36]
Hi everyone,

I'm using your packages "yingtools2" for the LEfSe function. I would like to know if there a way to perform LEfSe on changes (log ratio) ?
I explain my study :
we've data for several groups at 2 time points and we want to find impacted taxa between groups using the change from baseline (log ratio). Is it feasible ?
Is there a way to define classes to have an identical study ?

Another question is how you deal with negative or 0 values ?
I run LEfSe with the same dataset and different value in there and I didn't obtain the same number of rows in the result table

Thanks in advance !

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
