### ISSUE TITLE
repo-free path/URL for package functions?

### ISSUE THREAD

**Issue by noamross** [rdrr-io/rdrr-issues#37]
The pkgdown package is currently hoping to use your site as a place to link to function documentation (See https://github.com/r-lib/pkgdown/issues/998).

The challenge is that we don't necessarily know the repo (CRAN/BioC/GitHub) of the function in generating the URL.  Currently, linking works like this:

```
paste0("https://www.rdocumentation.org/packages/", package, "/topics/", rdname)
```

For rdrr.io, we would need the repo to do this, like so

```
paste0("https://rdrr.io/", REPO, "/", package, "/man/", rdname, "html")
```

CRAN and BioC respect each others' namespaces, I believe, and I think Rdocumentation defaults to CRAN or BioC if they have a common name with a GitHub package.  Is there a way to link to a function in this way in rdrr.io without knowing the repo?

**Comment by ihowson** [comment]
Not right now, but I can add it easily.

How about I make the pattern:

`https://rdrr.io/pkg/", package, "/man/", rdname, ".html"`

and it'll redirect to CRAN/BioC/RForge in that order, if found, otherwise search within GitHub?

**Comment by noamross** [comment]
Sounds great!

**Comment by ihowson** [comment]
This should be working now -- let me know how it goes!

e.g.
https://rdrr.io/pkg/ggplot2/
https://rdrr.io/pkg/ggplot2/man/guide_legend.html
https://rdrr.io/pkg/a4/

**Comment by jayhesselberth** [comment]
Thanks, this looks promising.

Do you also build the documentation for internal R libraries? 

These links to internal libraries don't work currently:

https://rdrr.io/pkg/base/man/library.html
https://rdrr.io/pkg/utils/man/install.packages.html

Edit: I found the base packages (https://rdrr.io/r/utils/install.packages.html). I updated pkgdown to generate the correct links for base packages.

**Comment by noamross** [comment]
Thank you!

**Comment by ihowson** [comment]
I can add the internal libraries to `/pkg` if you like -- or are you happy with the `/r` endpoint?

**Comment by jayhesselberth** [comment]
We are all set in pkgdown, will get back to you if we have issues. Thanks for seeing to this quickly.

**Comment by ihowson** [comment]
No problem!

**Comment by larmarange** [comment]
If you could add the internal libraries to `/pkg` it would be great!!!

I'm also in the process of generating documentation link on a R blog in French: http://larmarange.github.io/analyse-R/

Best regards

**Comment by ihowson** [comment]
R base packages should now resolve properly e.g.

https://rdrr.io/pkg/base/man/library.html
https://rdrr.io/pkg/utils/man/install.packages.html

Let me know if you have any more issues!
