### ISSUE TITLE
Advise people to install packages from github with 'remotes' instead of 'devtools'

### ISSUE THREAD

**Issue by trevorld** [rdrr-io/rdrr-issues#38]
Not too long ago the ``remotes`` package was spun out of ``devtools``.  Only installing ``remotes`` instead of ``devtools`` should install less extraneous packages to user's machines and may also avoid in the future user's getting a ``DeprecationWarning`` from ``devtools`` (telling them to use ``remotes`` instead like what I see if I try to use ``devtools::revdep_check``after they moved the ``revdep_check`` code to an outside package).

So advise something like:

````
install.packages("remotes")
remotes::install_github("username/pkgname")
````
instead of 
````
install.packages("devtools")
library("devtools")
install_github("username/pkgname")
````

**Comment by ihowson** [comment]
Should be fixed e.g. https://rdrr.io/github/00mathieu/noaaQuake/

Let me know if not!
