### ISSUE TITLE
smart dynamic select input

### ISSUE THREAD

**Issue by robertoromor** [rdrr-io/rdrr-issues#39]
If you are familiar with the SEARCH OPTION featured within a DT datatable in shiny you should know that if you render a dataframe  that has two columns "Name" and "Phone", and then you search for  either the name or phone you will get the column you are looking for. 

I have been trying to find something analogous to this functionality but for a SelectInput widget that will allow me to find Name or Phone regardless of the input that I give it and go look into the complete dataframe.

Do you know any widget that mirrors  the search option for a DT datatable??

Best, 

Roberto R.

**Comment by ihowson** [comment]
Hi Roberto,

Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
