### ISSUE TITLE
Provide a list of installed packages in snippets

### ISSUE THREAD

**Issue by sneumann** [rdrr-io/rdrr-issues#44]
Hi,
on https://rdrr.io/snippets/ it says "There are over three thousand R packages preloaded.".
It would be cool to have a list *which* packages that is. That list could be part 
of the data dump #41 .

Also, document somewhere how to (make it easier) to have a package be supported: 
do I have to provide a (bio)conda package ? Does it have to run/install on a particular 
Docker image without further system dependencies ? Anything else ?

Yours, Steffen

**Comment by ihowson** [comment]
List of installed packages is now at https://rdrr.io/snippets/installed/

For new packages, right now it's anything installable through `library.install()` (so anything on CRAN and Bioconductor). Outside dependencies are OK so long as they're installable on Ubuntu 14.04. But if you've got special requirements, let me know and I'll try to accomodate them.
