### ISSUE TITLE
jsontreeviewOutput not working 

### ISSUE THREAD

**Issue by pcchauhan120** [rdrr-io/rdrr-issues#47]
Hi,
 jsonviewouput works fine for me.But I am trying to use the jsonTreeViewOutput which is not rendering the tree...I am not getting any error but the tree is also not getting rendered.
My code is as follows:

library(jsonview)
library(shiny)
library(httr)
library(listviewer)
ui <- fluidPage(
  
  sidebarLayout(
    sidebarPanel(
      actionButton("go","get info")
    ),
    
    mainPanel(
      jsontreeviewOutput("my_tree_info") 
    )
  )
)

server <- function(input, output) {
  
  my_details <- eventReactive(input$go, {
    my_url<-"https://api.github.com/users/hadley/orgs"
    z<-GET(my_url)
    x<-content(z,as="parsed")
    txt<-toJSON(x)
    return(txt)
  })
  
 
  output$my_tree_info <- renderJsontreeview({
    
    json_tree_view(my_details())
  })
}

shinyApp(ui = ui, server = server)

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
