### ISSUE TITLE
[Feature Request] possibility to pass a FUNgenerator

### ISSUE THREAD

**Issue by kurt-o-sys** [rdrr-io/rdrr-issues#48]
In order to be able to have hybrid optimization possible, it would be great to be able to update the optimization function as one progresses through the swarm optimization.

Use case: using SA together with PSO, one could adapt the SA parameters on each next generation (e.g. lowering initial T, lowering tolerance etc). 

Instead of passing a FUN, one could pass a FUNgenerator, which also gets the iteration number (and optionally other properties of the swarm).

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
