### ISSUE TITLE
2012 Andy Field Discovering statistics with r robust packages vs. new robust packages

### ISSUE THREAD

**Issue by balazsgonczy** [rdrr-io/rdrr-issues#49]
Hello guys! 
I am new to this R program (with just a half a year experience) and having issues with the robust methods that are used in the Andy Field book (2012 Andy Field Discovering statistics with r ). Can I ask for some help? For example compared to the 2012 version of the Wilcox packages where the tsplit function had a syntax like this: tsplit(levels of factor A, levels of factor B, data, tr= .2) and the new one: tsplit(formula, random, data, tr = 0.2) 
Can I ask you how can I make the new tsplit function work like the old one? What do the formula and random parts stand for? 
Thank you very much for the help in advance!

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!

**Comment by balazsgonczy** [comment]
Sorry for the trouble!
Can you suggest me a place where I can found willing people to help my
issue?

>
