### ISSUE TITLE
Addison Klinke ASTM E1049 Rainflow in R

### ISSUE THREAD

**Issue by JWWHouse** [rdrr-io/rdrr-issues#59]
Great package.  I'm having some issues with artificial (i.e., test) data.  I'll submit an issue with test data.

**Comment by JWWHouse** [comment]
Works as expected with Python Project Rainflow test data, (https://pypi.org/project/rainflow/), but when I create test data with know number of cycles CountCycles either creates errors, returns an empty table, or returns results without summarizing into tables (i.e., returns each cycle discovered instead of binning into summary table.  Error summary and test data is attached: TestTimeHistory3.txt is a single amplitude with 100 cycles.  TestTimeHistory4.txt is 100 cycles with amplitude +/-100 and 50 cycles with amplitude +/- 50. TestTimeHistory6.txt is 1650 cycles of 10 differenent amplitudes, randomized.  File AKRainflowError.txt shows some output with error messages or empty output tables.

[AKRainflowError.txt](https://github.com/rdrr-io/rdrr-issues/files/4440542/AKRainflowError.txt)

[TestTimeHistory3.txt](https://github.com/rdrr-io/rdrr-issues/files/4440535/TestTimeHistory3.txt)

[TestTimeHistory4.txt](https://github.com/rdrr-io/rdrr-issues/files/4440518/TestTimeHistory4.txt)

[TestTimeHistory6.txt](https://github.com/rdrr-io/rdrr-issues/files/4440521/TestTimeHistory6.txt)

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!

**Comment by JWWHouse** [comment]
I am in conversation with the author, Addison Klinke, and he asked me to
create an issue to formally track the problem and to transmit examples/data
files.  Also, the web page for his code asks that an issue be created
before adding comments or improvements. Shouldn't the issue be closed by
the author? I'd ask that you reopen the issue until the author either
resolves it or points out my error.  Thanks.

**Comment by ihowson** [comment]
This is the issue tracker for the rdrr.io website. For issues with the rainflow R package, you probably want https://github.com/addisonklinke/rainflow
