### ISSUE TITLE
Confidence interval for randef function

### ISSUE THREAD

**Issue by hynekcigler** [rdrr-io/rdrr-issues#60]
Hi, I needed confidence interval fo random effect in mixedmirt object. I wanted to use draws used by randef function, but I have got this message:
```
> fit1 <- mixedmirt(dat2[3:13], covdata = dat2[1:2], 
+                   itemtype = "Rasch",
+                   model = "X = 1-9",
+                   lr.random	= list(~ 1 | hodnotitel, 
+                                    ~ 1 | jmeno), 
+                   SE = TRUE, calcNull = TRUE)
> result1 <- randef(fit1, ndraws = 2000, thin = 10, return.draws = TRUE)
Error in `*tmp*`[[j + 1L]] : subscript out of bounds
```
(fit 1 is an object of MixedClass)

Am I missing something? Am I correct that these posterior samples can be used to estimate confidence intervals?

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
