### ISSUE TITLE
download_ERA issue

### ISSUE THREAD

**Issue by jcepedaabad** [rdrr-io/rdrr-issues#61]
Hi. 
I'm trying to use download_ERA code, however, I always obtain this error code message "Error in wf_check[[correct]] : 
  attempt to select less than one element in get1index"

I'm writting this 

download_ERA(
  Variable = "2m_temperature",
  Type = "reanalysis",
  DataSet = "era5-land",
  DateStart = "1981-01-01",
  DateStop = Sys.Date() - 100,
  TResolution = "hour",
  TStep = 1,
  Extent = extent(-76, -65, -55, -16),
  Dir = getwd(),
  FileName = NULL,
  API_User = "XXXX",
  API_Key = "XXXX")

Do you know what happen?

regards!

**Comment by ihowson** [comment]
Thanks for getting in touch!

Unfortunately, I'm not the author of the packages on https://rdrr.io, and I'm not able to provide support for them. You should get in touch with the package authors listed on the package page.

Thanks,
Ian
