### ISSUE TITLE
Outdated version of package

### ISSUE THREAD

**Issue by xrobin** [rdrr-io/rdrr-issues#62]
The version of the pROC package available with the Snippet code runner is outdated.

Steps to reproduce:

1. Open https://rdrr.io/snippets/

2. Enter the following code and run:

    library(pROC)
    print(packageVersion("pROC"))

Output:
```
Type 'citation("pROC")' for a citation.
Attaching package: 'pROC'
The following objects are masked from 'package:stats':
    cov, smooth, var
[1] '1.14.0'
```

This version is very old and has been replaced more than 1 year ago. The current CRAN version of pROC is 1.16.2.

Is this expected?

Note: this is related with xrobin/pROC#79 where a user reported an error while running the examples ("Run the examples") button for [pROC's coords function](https://rdrr.io/cran/pROC/man/coords.html). It seems that the version available in the online docs https://rdrr.io/cran/pROC/ is up to date, and doesn't match the version installed with the snippet runner.

**Comment by ihowson** [comment]
1.16.2 is installed now
