### ISSUE TITLE
Explanation Of NWTCO Dataset in Survival Analysis

### ISSUE THREAD

**Issue by RohanMathur17** [rdrr-io/rdrr-issues#63]
https://rdrr.io/cran/survival/man/nwtco.html

The following link provides a dataset known as nwtco. The site doesn't clearly explain the variables - 'instit' & 'histol'.
Each of these columns have values 1 & 2 as possible variables, but there is no clear explanation of what they actually represent.

Can someone please explain the meaning of these 2 columns?

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
