### ISSUE TITLE
Error in library(babette) : there is no package called 'babette'

### ISSUE THREAD

**Issue by richelbilderbeek** [rdrr-io/rdrr-issues#66]
Hi @ihowson,

I think it is great that one can R code from the browser!

I noticed, however, that my own package goes wrong. I will report this nicely and would like to know if this is my bad or not :angel: .

When I go to the rdrr.io page of the CRAN version of `babette` at [https://rdrr.io/cran/babette/man/babette.html](https://rdrr.io/cran/babette/man/babette.html), I can find a first `babette` example. When I run it, it gives an error:

```
Error in library(babette) : there is no package called 'babette'
Execution halted
```

![Screenshot from 2020-10-26 15-20-45](https://user-images.githubusercontent.com/2098230/97184106-db830300-179e-11eb-9c56-525cf8369ece.png)

As `babette` is a CRAN package that (AFAICS) is working fine, I expected the example to run without errors. 

The same occurs when running a vignette, such as [https://rdrr.io/cran/babette/f/vignettes/demo.Rmd](https://rdrr.io/cran/babette/f/vignettes/demo.Rmd):

![Screenshot from 2020-10-26 15-16-16](https://user-images.githubusercontent.com/2098230/97183731-6b747d00-179e-11eb-902b-f709434a80cc.png)

I wonder if the error is on my side, although I do check my packages thoroughly on Travis CI and/or AppVeyor. If this is the case, I'd be happy to fix it myself of course. Else, I hope this will be fixed.

Cheers, Richel Bilderbeek

**Comment by ihowson** [comment]
I tried to install `babette`, but unfortunately Snippets is running an oldish version of R (3.4.4) which isn't compatible with `babette`. 

I'm working on updating the R version but it's going to take some time. I will keep the ticket open so I know to make sure it works.

Thanks for getting in touch!

**Comment by richelbilderbeek** [comment]
That's a clear reason, thanks! And good luck updating your awesome tool!

**Comment by ihowson** [comment]
@richelbilderbeek The R version on Snippets has been updated, `babette` is installed and seems to be working. Let me know if you have any issues!

**Comment by richelbilderbeek** [comment]
@ihowson thanks so much for your awesome work!
