### ISSUE TITLE
cant install obrl-soil/h3jsr

### ISSUE THREAD

**Issue by twiebke** [rdrr-io/rdrr-issues#77]
I get "free(): invalid pointer
Aborted (core dumped)
ERROR: lazy loading failed for package ‘h3jsr’"
remotes::install_github("obrl-soil/h3jsr")
Downloading GitHub repo obrl-soil/h3jsr@HEAD
✔  checking for file ‘/tmp/RtmpfcxHni/remotes2c1f20bdc16c/obrl-soil-h3jsr-3d2b654/DESCRIPTION’ ...
─  preparing ‘h3jsr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘h3jsr_1.2.0.tar.gz’
   
Installing package into ‘/home/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘h3jsr’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
free(): invalid pointer
Aborted (core dumped)
ERROR: lazy loading failed for package ‘h3jsr’
* removing ‘/home/R/x86_64-pc-linux-gnu-library/4.0/h3jsr’
Fehler: Failed to install 'h3jsr' from GitHub:
  (konvertiert von Warnung) installation of package ‘/tmp/RtmpfcxHni/file2c1f47b0862a/h3jsr_1.2.0.tar.gz’ had non-zero exit status

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
