### ISSUE TITLE
Repo Deleted

### ISSUE THREAD

**Issue by afitz-gmu** [rdrr-io/rdrr-issues#78]
Hi, 

There is a repo that I am working on with a co-author and we need the repo deleted from public view so we deleted it but its still showing up on rdrr.io with all of the files. Is there a way to get it deleted from there too? 

https://rdrr.io/github/sneha-matrix/GenomicsVisualization/f/

Thanks

**Comment by ihowson** [comment]
I've removed it. Thanks for letting me know!
