### ISSUE TITLE
Conflicting message between warning message and other similar warning messages (p-value)

### ISSUE THREAD

**Issue by kdl0013** [rdrr-io/rdrr-issues#85]
I am running an adf test on a time series using the null alternative of 'explosive'.  I am receiving an odd error message that states the p-value is smaller than printed p-value.  Why would it tell me that the p-value is smaller than 0.99?  For all the other printed statements in your functions (kpss included) there will only be a warning message for "p-value greater than printed value {0.1}" or "p-value smaller than printed value {0.01}"

I have looked at the source code, but I did not see where there statements are printed from.  Thank you for any clarification.

`adf.test(rzsm_zoo_wk, alternative = 'explosive') `

Output:
Augmented Dickey-Fuller Test

data:  rzsm_zoo_wk
Dickey-Fuller = -8.7707, Lag order = 12, p-value = 0.99
alternative hypothesis: explosive

Warning message:
In adf.test(rzsm_zoo_wk, alternative = "explosive") :
  p-value smaller than printed p-value

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
