### ISSUE TITLE
error related to bed2vcf

### ISSUE THREAD

**Issue by ghost** [rdrr-io/rdrr-issues#88]
Hello,
I am trying to convert my bed file to vcf file. But its showing some error.
The command:
bed2vcf(mashr_hg38_liftover,filename =finali, zero.based = TRUE, header = NULL, fasta = NULL)
the error:
Check for larger start position... PASS.
 * Check if zero based... PASS

ERROR: Sorry, the program is stopping until problem features are fixed.  
    You can try using is.valid.region and fix.region functions to debug
Error in is.valid.region(x, throw.error = TRUE, check.zero.based = check.zero.based,  : 
Can you please tell me how should I use this two options to reduce the error?
Thank You.

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
