### ISSUE TITLE
pls close CMIP6tools 

### ISSUE THREAD

**Issue by kongdd** [rdrr-io/rdrr-issues#92]
Dear `rdrr` ,

I am the author of CMIP6tools. 
https://rdrr.io/github/CUG-atmos/CMIP6tools/man/CMIP6tools-package.html

I do not want to my package occur in rdrr.
I have turned this repository into private. But it is still visible.

Please help to delete it.
Thanks for your help!

By the way, any idea about how to forbid rdrr crawl github R packcage?

**Comment by ihowson** [comment]
I've deleted the package.

There is no automated way to prevent GitHub crawling at this time. If you've got packages you'd like me to block from crawling, let me know.

Thanks for getting in touch!

**Comment by kongdd** [comment]
Thanks for your quick response.
