### ISSUE TITLE
RStudio keras package callbacks.R bug in on_predict end

### ISSUE THREAD

**Issue by tedtoal** [rdrr-io/rdrr-issues#93]
Hope this is the right place for this bug report.

In rstudio/keras within rdrr.io within the R folder in file callbacks.R, there is a line missing which results in the custom lambda callback named on_predict_end() to not work.  Here is the code from that file and you can see that on_predict_end() is missing:
```
args <- list(
    on_epoch_begin = on_epoch_begin,
    on_epoch_end = on_epoch_end,
    on_batch_begin = on_batch_begin,
    on_batch_end = on_batch_end,
    on_train_begin = on_train_begin,
    on_train_end = on_train_end,
    on_train_batch_begin = on_train_batch_begin,
    on_train_batch_end = on_train_batch_end,
    on_predict_batch_begin = on_predict_batch_begin,
    on_predict_batch_end = on_predict_batch_end,
    on_predict_begin = on_predict_begin,
    on_test_batch_begin = on_test_batch_begin,
    on_test_batch_end = on_test_batch_end,
    on_test_begin = on_test_begin,
    on_test_end = on_test_end
  )
```

I assume this is why I'm unable to get the on_predict_end callback working.

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
