### ISSUE TITLE
How to merge image generated by plotClarkeGrid with other functions?

### ISSUE THREAD

**Issue by stealassassin** [rdrr-io/rdrr-issues#94]
Hi, I have generated a Clarke error grid image with some clinical data, however, I found it seems difficult to add OLS regression line from the same dataset to the CEG image, whenever using ade4 library or ggplotify. Do you have some advice?
Thanks a lot!

BR,

Sakura

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
