### ISSUE TITLE
na_pad returns 0 and not NA with runner

### ISSUE THREAD

**Issue by baccione-eawag** [rdrr-io/rdrr-issues#98]
In my hands this happens:

```
library(runner)
runner(c(1,2,3,4,5,6), k=3, f=sum, lag=-2, na_pad=T)
[1]  6  9 12 15  0  0
```

According to the Docs:
```
na_pad | (logical single value) 
Whether incomplete window should return NA (if na_pad = TRUE) Incomplete window is when some parts of the window are out of range.
```

I was expecting:
`[1]  6  9 12 15  NA NA`

This kind of makes it not usable for me as I cannot discern a valid 0 from a missing.

**Comment by ihowson** [comment]
Thanks for getting in touch!

This issue tracker is just for website issues. We're not able to provide technical support for individual packages. Sorry!
